[build]
  command = "ng build --configuration=production && cp dist/e-commerce/browser/index.csr.html dist/e-commerce/browser/index.html"
  publish = "dist/e-commerce/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200